name: daily-cron
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl \
          --url 'https://ai-blog-api-production.up.railway.app/post' \
          --header 'Authorization: Bearer ${{ secrets.NEXT_API_KEY }}'
