name: cron-revalidate
on:
  schedule:
    - cron: "5 1 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: On demand ISR
        run: |
          curl \
          --url 'https://ai-blog-ten.vercel.app/api/revalidate' \
          --header 'Authorization: Bearer ${{ secrets.NEXT_API_KEY }}'
